import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import { UserProvider } from "@auth0/nextjs-auth0/client";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <UserProvider>
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      <body className="content-around flex-col"
      >

        <Navbar/>
        {children}
    

      </body>
      </html>
      </UserProvider>
  );
}
